Calcinai\Siri\Datex\PoorEnvironmentConditionsType:
    properties:
        poorEnvironmentType:
            expose: true
            access_type: public_method
            serialized_name: poorEnvironmentType
            xml_element:
                namespace: 'http://datex2.eu/schema/1_0/1_0'
            accessor:
                getter: getPoorEnvironmentType
                setter: setPoorEnvironmentType
            type: string
        precipitationDetail:
            expose: true
            access_type: public_method
            serialized_name: precipitationDetail
            xml_element:
                namespace: 'http://datex2.eu/schema/1_0/1_0'
            accessor:
                getter: getPrecipitationDetail
                setter: setPrecipitationDetail
            type: Calcinai\Siri\Datex\PrecipitationDetailType
        visibility:
            expose: true
            access_type: public_method
            serialized_name: visibility
            xml_element:
                namespace: 'http://datex2.eu/schema/1_0/1_0'
            accessor:
                getter: getVisibility
                setter: setVisibility
            type: Calcinai\Siri\Datex\VisibilityType
        pollutionMeasurement:
            expose: true
            access_type: public_method
            serialized_name: pollutionMeasurement
            xml_element:
                namespace: 'http://datex2.eu/schema/1_0/1_0'
            accessor:
                getter: getPollutionMeasurement
                setter: setPollutionMeasurement
            xml_list:
                inline: true
                entry_name: pollutionMeasurement
                namespace: 'http://datex2.eu/schema/1_0/1_0'
            type: array<Calcinai\Siri\Datex\PollutionMeasurementType>
        temperature:
            expose: true
            access_type: public_method
            serialized_name: temperature
            xml_element:
                namespace: 'http://datex2.eu/schema/1_0/1_0'
            accessor:
                getter: getTemperature
                setter: setTemperature
            type: Calcinai\Siri\Datex\TemperatureType
        wind:
            expose: true
            access_type: public_method
            serialized_name: wind
            xml_element:
                namespace: 'http://datex2.eu/schema/1_0/1_0'
            accessor:
                getter: getWind
                setter: setWind
            type: Calcinai\Siri\Datex\WindType
        poorEnvironmentConditionsExtension:
            expose: true
            access_type: public_method
            serialized_name: poorEnvironmentConditionsExtension
            xml_element:
                namespace: 'http://datex2.eu/schema/1_0/1_0'
            accessor:
                getter: getPoorEnvironmentConditionsExtension
                setter: setPoorEnvironmentConditionsExtension
            type: Calcinai\Siri\Datex\ExtensionType
