Calcinai\Siri\Objects\ProductionTimetableServiceCapabilitiesStructureType\TopicFilteringAType:
    properties:
        filterByValidityPeriod:
            expose: true
            access_type: public_method
            serialized_name: FilterByValidityPeriod
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getFilterByValidityPeriod
                setter: setFilterByValidityPeriod
            type: bool
        filterByOperatorRef:
            expose: true
            access_type: public_method
            serialized_name: FilterByOperatorRef
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getFilterByOperatorRef
                setter: setFilterByOperatorRef
            type: bool
        filterByLineRef:
            expose: true
            access_type: public_method
            serialized_name: FilterByLineRef
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getFilterByLineRef
                setter: setFilterByLineRef
            type: bool
        filterByVersionRef:
            expose: true
            access_type: public_method
            serialized_name: FilterByVersionRef
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getFilterByVersionRef
                setter: setFilterByVersionRef
            type: bool
