Calcinai\Siri\Objects\ProductionTimetableDeliveryStructureType:
    properties:
        version:
            expose: true
            access_type: public_method
            serialized_name: version
            accessor:
                getter: getVersion
                setter: setVersion
            xml_attribute: true
            type: string
        datedTimetableVersionFrame:
            expose: true
            access_type: public_method
            serialized_name: DatedTimetableVersionFrame
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getDatedTimetableVersionFrame
                setter: setDatedTimetableVersionFrame
            xml_list:
                inline: true
                entry_name: DatedTimetableVersionFrame
                namespace: 'http://www.siri.org.uk/siri'
            type: array<Calcinai\Siri\Objects\DatedTimetableVersionFrame>
        extensions:
            expose: true
            access_type: public_method
            serialized_name: Extensions
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getExtensions
                setter: setExtensions
            type: Calcinai\Siri\Objects\Extensions
