Calcinai\Siri\ProducerRequestEndpointStructureType:
    properties:
        address:
            expose: true
            access_type: public_method
            serialized_name: Address
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getAddress
                setter: setAddress
            type: string
        producerRef:
            expose: true
            access_type: public_method
            serialized_name: ProducerRef
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getProducerRef
                setter: setProducerRef
            type: Calcinai\Siri\ParticipantRefStructureType
        messageIdentifier:
            expose: true
            access_type: public_method
            serialized_name: MessageIdentifier
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getMessageIdentifier
                setter: setMessageIdentifier
            type: Calcinai\Siri\MessageQualifierStructureType
