Calcinai\Siri\ProductCategoriesDeliveryStructureType:
    properties:
        version:
            expose: true
            access_type: public_method
            serialized_name: version
            accessor:
                getter: getVersion
                setter: setVersion
            xml_attribute: true
            type: string
        productCategory:
            expose: true
            access_type: public_method
            serialized_name: ProductCategory
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getProductCategory
                setter: setProductCategory
            xml_list:
                inline: true
                entry_name: ProductCategory
                namespace: 'http://www.siri.org.uk/siri'
            type: array<Calcinai\Siri\ProductCategoryStructureType>
        extensions:
            expose: true
            access_type: public_method
            serialized_name: Extensions
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getExtensions
                setter: setExtensions
            type: Calcinai\Siri\Extensions
