Calcinai\Siri\ProductionTimetableServiceCapabilitiesStructureType\SubscriptionPolicyAType:
    properties:
        hasIncrementalUpdates:
            expose: true
            access_type: public_method
            serialized_name: HasIncrementalUpdates
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getHasIncrementalUpdates
                setter: setHasIncrementalUpdates
            type: bool
