Calcinai\Siri\Objects\ProductCategoryStructureType:
    properties:
        productCategoryCode:
            expose: true
            access_type: public_method
            serialized_name: ProductCategoryCode
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getProductCategoryCode
                setter: setProductCategoryCode
            type: string
        name:
            expose: true
            access_type: public_method
            serialized_name: Name
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getName
                setter: setName
            type: Calcinai\Siri\Objects\NaturalLanguageStringStructureType
        icon:
            expose: true
            access_type: public_method
            serialized_name: Icon
            xml_element:
                namespace: 'http://www.siri.org.uk/siri'
            accessor:
                getter: getIcon
                setter: setIcon
            type: string
